<a href="https://colab.research.google.com/github/SalmiFatimaZahra/Gestion-des-salaires-des-employ-s-dans-une-entreprise-/blob/main/GenerativeAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [ ]:
voc_size = 10000

In [ ]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr)

[[4146, 1160, 3669, 6505], [4146, 1160, 3669, 4218], [4146, 6254, 3669, 6261], [9262, 6157, 6068, 22, 2833], [9262, 6157, 6068, 22, 8875], [8156, 4146, 6355, 3669, 3456], [9763, 2805, 2045, 22]]


In [ ]:
from tensorflow.keras.utils import pad_sequences

sent_length = 8

embedded_docs = pad_sequences(
    one_hot_repr,
    padding='pre',
    maxlen=sent_length
)

print(embedded_docs)

[[   0    0    0    0 4146 1160 3669 6505]
 [   0    0    0    0 4146 1160 3669 4218]
 [   0    0    0    0 4146 6254 3669 6261]
 [   0    0    0 9262 6157 6068   22 2833]
 [   0    0    0 9262 6157 6068   22 8875]
 [   0    0    0 8156 4146 6355 3669 3456]
 [   0    0    0    0 9763 2805 2045   22]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

dim = 10

model = Sequential()
model.add(
    Embedding(
        voc_size,
        dim,
        input_length=sent_length
    )
)

model.compile('adam', 'mse')

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
embedding_output = model.predict(embedded_docs)
print(embedding_output.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step
(7, 8, 10)


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 4146, 1160, 3669, 6505], dtype=int32)

In [ ]:
model.predict(
    embedded_docs[0].reshape(1, -1)
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[[-0.03327094,  0.00882399, -0.01064098, -0.01378609,
         -0.04709115, -0.00025009,  0.02805171, -0.0170595 ,
         -0.00112052,  0.00967156],
        [-0.03327094,  0.00882399, -0.01064098, -0.01378609,
         -0.04709115, -0.00025009,  0.02805171, -0.0170595 ,
         -0.00112052,  0.00967156],
        [-0.03327094,  0.00882399, -0.01064098, -0.01378609,
         -0.04709115, -0.00025009,  0.02805171, -0.0170595 ,
         -0.00112052,  0.00967156],
        [-0.03327094,  0.00882399, -0.01064098, -0.01378609,
         -0.04709115, -0.00025009,  0.02805171, -0.0170595 ,
         -0.00112052,  0.00967156],
        [-0.04153963, -0.0024793 , -0.02779198,  0.0076925 ,
          0.0493266 ,  0.03046833, -0.02541792, -0.00742538,
          0.02520212,  0.0029997 ],
        [ 0.04129889,  0.00981175, -0.03570778, -0.02273846,
         -0.02886789, -0.02101051, -0.00198255,  0.00634704,
          0.01036962, -0.00747911],
        [ 0.01839516,  0.01317951,  0.00264952,  0.0